name : Auto Deploy StarAlliance

on: 
  push:
    branches:
      - main

jobs :
  ftp-deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: NPM INSTALL
        run: npm install

      - name: BUILD REACT APP
        run: npm run build

      - name: deploy by ftp on godaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3

        with:
         server:   148.72.62.9
         username: deploy@starallianceaviation.com
         password: ${{secrets.FTP_PASSWORD}}
         protocols: ftps
         port: 21
         local-dir: dist/
         server-dir: /
         dangerous-clean-slate: false  

# bhai agar yeah true hua toh pahle sare file ko remove karega phir ja ke upload yeah slow bahut hoga deploy ke time and false reflect only changes    


        

